{% if enable_data_quality %}
ATTACH DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT TO TABLE {{ employee_db() }}.RAW.EMPLOYEES ON (EMPLOYEE_ID)
 EXPECTATION EMPLOYEE_ID_NOT_NULL (VALUE = 0);
DEFINE DATA METRIC FUNCTION {{ employee_db() }}.GOVERNANCE.NON_POSITIVE_SALARY_COUNT(T TABLE(SALARY NUMBER)) RETURNS NUMBER AS $$ SELECT COUNT_IF(SALARY <= 0) FROM T $$;
ATTACH DATA METRIC FUNCTION {{ employee_db() }}.GOVERNANCE.NON_POSITIVE_SALARY_COUNT TO TABLE {{ employee_db() }}.RAW.EMPLOYEES ON (SALARY)
 EXPECTATION SALARY_MUST_BE_POSITIVE (VALUE = 0);
{% endif %}
