DEFINE TAG {{ employee_db() }}.GOVERNANCE.DATA_CLASSIFICATION ALLOWED_VALUES 'PII','INTERNAL','PUBLIC' COMMENT='Simple classification tag';
ATTACH TAG {{ employee_db() }}.GOVERNANCE.DATA_CLASSIFICATION='PII' TO TABLE {{ employee_db() }}.RAW.EMPLOYEES;

DEFINE MASKING POLICY {{ employee_db() }}.GOVERNANCE.EMAIL_MASK AS (VAL VARCHAR) RETURNS VARCHAR ->
 CASE WHEN IS_DATABASE_ROLE_IN_SESSION('{{ employee_db() }}.ENGINEER') OR IS_DATABASE_ROLE_IN_SESSION('{{ employee_db() }}.DBT_DEVELOPER') THEN VAL
      WHEN VAL IS NULL THEN NULL ELSE REGEXP_REPLACE(VAL,'^(.).*(@.*)$','\1*****\2') END
 COMMENT='Masks email for non-engineer consumers';
