-- DCM can define masking policies but cannot yet attach them to columns.
-- Replace <DB_NAME> with EMPLOYEE_ANALYTICS_DEV / _STAGE / _PROD.
ALTER TABLE EMPLOYEE_ANALYTICS_DEV.RAW.EMPLOYEES MODIFY COLUMN EMAIL SET MASKING POLICY EMPLOYEE_ANALYTICS_DEV.GOVERNANCE.EMAIL_MASK;
