DEFINE TABLE {{ employee_db() }}.RAW.EMPLOYEES (
 EMPLOYEE_ID NUMBER NOT NULL, EMPLOYEE_NAME VARCHAR(200), EMAIL VARCHAR(320), DEPARTMENT_ID NUMBER,
 JOB_TITLE VARCHAR(150), JOIN_DATE DATE, EXIT_DATE DATE, EMPLOYMENT_STATUS VARCHAR(30), SALARY NUMBER(12,2),
 UPDATED_AT TIMESTAMP_NTZ, LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
{% if enable_data_quality %}DATA_METRIC_SCHEDULE='TRIGGER_ON_CHANGES'{% endif %}
COMMENT='Employee master data';

DEFINE TABLE {{ employee_db() }}.RAW.DEPARTMENTS (
 DEPARTMENT_ID NUMBER NOT NULL, DEPARTMENT_NAME VARCHAR(150), DEPARTMENT_HEAD VARCHAR(200), COST_CENTER VARCHAR(50),
 LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT='Department reference data';

DEFINE TABLE {{ employee_db() }}.RAW.EMPLOYEE_EVENTS (
 EVENT_ID NUMBER NOT NULL, EMPLOYEE_ID NUMBER NOT NULL, EVENT_TYPE VARCHAR(50), EVENT_DATE DATE,
 OLD_VALUE VARCHAR(500), NEW_VALUE VARCHAR(500), LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT='Employee lifecycle events';
