USE ROLE EMPLOYEE_DBT;
USE WAREHOUSE EMPLOYEE_TRANSFORM_WH_PROD;
USE DATABASE EMPLOYEE_ANALYTICS_PROD;

SHOW SCHEMAS IN DATABASE EMPLOYEE_ANALYTICS_PROD;

SHOW DBT PROJECTS
  IN SCHEMA EMPLOYEE_ANALYTICS_PROD.DBT_PROJECTS;

SHOW VIEWS IN SCHEMA EMPLOYEE_ANALYTICS_PROD.STAGING;
SHOW TABLES IN SCHEMA EMPLOYEE_ANALYTICS_PROD.ANALYTICS;

SELECT COUNT(*) AS DIM_EMPLOYEES_ROWS
FROM EMPLOYEE_ANALYTICS_PROD.ANALYTICS.DIM_EMPLOYEES;

SELECT *
FROM EMPLOYEE_ANALYTICS_PROD.ANALYTICS.AGG_DEPARTMENT_SUMMARY
ORDER BY DEPARTMENT_NAME;
