--This is to establish the project objects and roles.
USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS DCM_CONTROL;
CREATE SCHEMA IF NOT EXISTS DCM_CONTROL.PROJECTS;

--Creating Deployment Roles
CREATE ROLE IF NOT EXISTS EMP_DCM_DEV_DEPLOYER;
CREATE ROLE IF NOT EXISTS EMP_DCM_STAGE_DEPLOYER;
CREATE ROLE IF NOT EXISTS EMP_DCM_PROD_DEPLOYER;

--Creating Functional Roles
CREATE ROLE IF NOT EXISTS EMPLOYEE_ENGINEER;
CREATE ROLE IF NOT EXISTS EMPLOYEE_DBT;
CREATE ROLE IF NOT EXISTS EMPLOYEE_ANALYST;

GRANT USAGE ON DATABASE DCM_CONTROL TO ROLE EMP_DCM_DEV_DEPLOYER;
GRANT USAGE ON SCHEMA DCM_CONTROL.PROJECTS TO ROLE EMP_DCM_DEV_DEPLOYER;
GRANT CREATE DCM PROJECT ON SCHEMA DCM_CONTROL.PROJECTS TO ROLE EMP_DCM_DEV_DEPLOYER;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE EMP_DCM_DEV_DEPLOYER;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE EMP_DCM_DEV_DEPLOYER;
GRANT MANAGE GRANTS ON ACCOUNT TO ROLE EMP_DCM_DEV_DEPLOYER;

GRANT USAGE ON DATABASE DCM_CONTROL TO ROLE EMP_DCM_STAGE_DEPLOYER;
GRANT USAGE ON SCHEMA DCM_CONTROL.PROJECTS TO ROLE EMP_DCM_STAGE_DEPLOYER;
GRANT CREATE DCM PROJECT ON SCHEMA DCM_CONTROL.PROJECTS TO ROLE EMP_DCM_STAGE_DEPLOYER;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE EMP_DCM_STAGE_DEPLOYER;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE EMP_DCM_STAGE_DEPLOYER;
GRANT MANAGE GRANTS ON ACCOUNT TO ROLE EMP_DCM_STAGE_DEPLOYER;

GRANT USAGE ON DATABASE DCM_CONTROL TO ROLE EMP_DCM_PROD_DEPLOYER;
GRANT USAGE ON SCHEMA DCM_CONTROL.PROJECTS TO ROLE EMP_DCM_PROD_DEPLOYER;
GRANT CREATE DCM PROJECT ON SCHEMA DCM_CONTROL.PROJECTS TO ROLE EMP_DCM_PROD_DEPLOYER;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE EMP_DCM_PROD_DEPLOYER;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE EMP_DCM_PROD_DEPLOYER;
GRANT MANAGE GRANTS ON ACCOUNT TO ROLE EMP_DCM_PROD_DEPLOYER;

--Replace with your own user in account
GRANT ROLE EMP_DCM_DEV_DEPLOYER TO USER DEEPTIA;
GRANT ROLE EMP_DCM_STAGE_DEPLOYER TO USER DEEPTIA;
GRANT ROLE EMP_DCM_PROD_DEPLOYER TO USER DEEPTIA;
GRANT ROLE EMPLOYEE_ENGINEER TO USER DEEPTIA;
GRANT ROLE EMPLOYEE_DBT TO USER DEEPTIA;
GRANT ROLE EMPLOYEE_ANALYST TO USER DEEPTIA;

USE DATABASE DCM_CONTROL; 
USE SCHEMA PROJECTS;

--Creating DCM project Objects
USE ROLE EMP_DCM_DEV_DEPLOYER;
CREATE DCM PROJECT IF NOT EXISTS EMPLOYEE_ANALYTICS_DEV COMMENT='Employee Analytics DEV DCM project';

USE ROLE EMP_DCM_STAGE_DEPLOYER; 
CREATE DCM PROJECT IF NOT EXISTS EMPLOYEE_ANALYTICS_STAGE COMMENT='Employee Analytics STAGE DCM project';

USE ROLE EMP_DCM_PROD_DEPLOYER; 
CREATE DCM PROJECT IF NOT EXISTS EMPLOYEE_ANALYTICS_PROD COMMENT='Employee Analytics PROD DCM project';
