-- OPTIONAL: only for Enterprise Edition accounts using DCM Data Quality expectations.
-- Snowflake trial accounts do not support Data Quality Monitoring / DMFs.
USE ROLE ACCOUNTADMIN;
GRANT EXECUTE DATA METRIC FUNCTION ON ACCOUNT TO ROLE EMP_DCM_DEV_DEPLOYER;
GRANT EXECUTE DATA METRIC FUNCTION ON ACCOUNT TO ROLE EMP_DCM_STAGE_DEPLOYER;
GRANT EXECUTE DATA METRIC FUNCTION ON ACCOUNT TO ROLE EMP_DCM_PROD_DEPLOYER;
GRANT DATABASE ROLE SNOWFLAKE.DATA_METRIC_USER TO ROLE EMP_DCM_DEV_DEPLOYER;
GRANT DATABASE ROLE SNOWFLAKE.DATA_METRIC_USER TO ROLE EMP_DCM_STAGE_DEPLOYER;
GRANT DATABASE ROLE SNOWFLAKE.DATA_METRIC_USER TO ROLE EMP_DCM_PROD_DEPLOYER;
