name: 02 - Validate Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read
  id-token: write
  pull-requests: write

env:
  SNOWFLAKE_USER: SVC_EMP_DCM_PROD
  SNOWFLAKE_ACCOUNT: ${{ vars.SNOWFLAKE_ACCOUNT }}
  SNOWFLAKE_CLI_FEATURES_ENABLE_DBT: true

jobs:
  dcm-prod-plan:
    runs-on: ubuntu-latest
    environment: DCM_PROD

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Snowflake CLI with OIDC
        uses: snowflakedb/snowflake-actions@v3
        with:
          use-oidc: true
          cli-version: "3.16"

      - name: Test Snowflake connection
        run: |
          snow connection test \
            --account "$SNOWFLAKE_ACCOUNT" \
            --user "$SNOWFLAKE_USER" \
            -x

      - name: Run PROD DCM PLAN
        run: |
          snow dcm plan \
            --target DCM_PROD \
            -x

  dbt-stage-validation:
    runs-on: ubuntu-latest
    environment: DCM_PROD

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Snowflake CLI with OIDC
        uses: snowflakedb/snowflake-actions@v3
        with:
          use-oidc: true
          cli-version: "3.23.0"

      - name: Test Snowflake connection
        run: |
          snow connection test \
            --account "$SNOWFLAKE_ACCOUNT" \
            --user "$SNOWFLAKE_USER" \
            -x

      - name: Check dbt project files
        run: |
          pwd
          find sources/dbt/employee_analytics -maxdepth 2 -type f | sort
          test -f sources/dbt/employee_analytics/dbt_project.yml
          test -f sources/dbt/employee_analytics/profiles.yml

      - name: Deploy dbt CI project to STAGE
        run: |
          snow --debug dbt deploy EMPLOYEE_ANALYTICS_DBT_CI \
            --source ./sources/dbt/employee_analytics \
            --default-target stage \
            --database EMPLOYEE_ANALYTICS_STAGE \
            --schema DBT_PROJECTS \
            --role EMPLOYEE_DBT \
            --warehouse EMPLOYEE_TRANSFORM_WH_STAGE \
            --account "$SNOWFLAKE_ACCOUNT" \
            --user "$SNOWFLAKE_USER" \
            -x

      - name: Run dbt build against STAGE
        run: |
          snow sql \
            -q "EXECUTE DBT PROJECT EMPLOYEE_ANALYTICS_STAGE.DBT_PROJECTS.EMPLOYEE_ANALYTICS_DBT_CI ARGS = 'build --target stage';" \
            --database EMPLOYEE_ANALYTICS_STAGE \
            --schema DBT_PROJECTS \
            --role EMPLOYEE_DBT \
            --warehouse EMPLOYEE_TRANSFORM_WH_STAGE \
            --account "$SNOWFLAKE_ACCOUNT" \
            --user "$SNOWFLAKE_USER" \
            -x